### ISSUE TITLE
support for UR v0.6.0

### ISSUE THREAD

**Issue by irousso** [heroku/predictionio-engine-ur#9]
Hey,
Version 0.6.0 of UR introduces (among other things)

> Complimentary Purchase aka Item-set Recommendations

We're wondering when this project will support v0.6.0 since currently we're deployed on AWS EC2 with that version, and that's the only thing keeping us from not moving away from AWS and switching to using heroku..

Thanks!

**Comment by mars** [comment]
Hi @irousso,

Our implementation of the Elasticsearch 5.x REST client in this Heroku fork of Universal Recommender would need to be revised with behavior to match the changes applied to the upstream ActionML Elasticsearch 1.x TCP client for Universal Recommender 0.6.0. This revision would require significant engineering work to ensure parity of the new Item-Set behavior.

A long-standing [pull-request on upstream UR](https://github.com/actionml/universal-recommender/pull/17) is the most authoritative source for the required work and the plan to get it done:

> Quite a bit required beyond this PR since PIO 0.12.0
>
> We are working on a UR 0.7.0, which will be ES5 only and have some significant speedups. First will be UR 0.6.1, which allows existing installations to upgrade to pio 0.12.0 with ES 1.x. Legacy systems need support too.

So, we’re not planning to upgrade this repo to version 0.6.0. At some point in the future, upstream UR will support Elasticsearch 5.x REST client; sounds like version 0.7.0 is the target. We plan to upgrade this repo at that time, resolving divergence of Elasticsearch client in our fork.

Of course, we’re open to contribution of an ES client upgrade to match 0.6.0 features.

Thanks for opening this issue!

**Comment by irousso** [comment]
Thanks!

**Comment by mars** [comment]
I'm going to leave this open, because until we can make the upgrade, it's not resolved.

**Comment by mars** [comment]
The Universal Recommender folks just pushed a [0.7.0-SNAPSHOT branch](https://github.com/actionml/universal-recommender/tree/0.7.0-SNAPSHOT). We'll be testing that for compatibility with PredictionIO on Heroku in the coming weeks.
